name: PR Checks

on:
  pull_request:
    branches:
      - working

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  comment_reports:
    name: Comment Reports
    runs-on: ubuntu-latest
    needs: [lint, unit_tests]
    steps:
      - name: Download Lint Report
        uses: actions/download-artifact@v4
        with:
          name: lint-report
          path: reports

      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: unit-test-report
          path: reports

      - name: Post comment with report links
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ✅ **Lint and Unit Tests Completed**
            - [Lint Report](./reports/lint-results-debug.html)
            - [Test Report](./reports/tests/testDebugUnitTest/index.html)
